query transportHistory($channelId: String!, $offset: Int, $limit: Int) {
  transportHistory(channelId: $channelId, offset: $offset, limit: $limit) {
    data
    userId
    seq
  }
}

query transportUsers($channelId: String!) {
  transportUsers(channelId: $channelId)
}

mutation enterChannel($input: ChannelInput!) {
  enterChannel(input: $input)
}

mutation exitChannel($input: ChannelInput!) {
  exitChannel(input: $input)
}

mutation sendData($input: SendDataInput!) {
  sendData(input: $input)
}

subscription receiveData($channelId: String!) {
  receiveData(channelId: $channelId) {
    data
    userId
    seq
  }
}
